"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import "../assets/style/common.scss";
import { useEffect } from "react";
import { Container, CssBaseline } from "@mui/material";
import { RecoilRoot } from "recoil";
import CustomLayout from "@/components/CustomLayout";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    if (!localStorage.getItem("settings")) {
      localStorage.setItem(
        "settings",
        JSON.stringify({
          theme: "light",
          elFontSize: 16,
          resolution: 1,
        })
      );
    }
    // const { elFontSize } = JSON.parse(localStorage.getItem("settings"));
    // document.documentElement.style.setProperty("font-size", `${elFontSize}px`);
    // document.documentElement.style.setProperty(
    //   "font-size",
    //   `${updateFontSize(elFontSize)}px`
    // );
  }, []);
  return (
    <html lang="ko">
      <body>
        <RecoilRoot>
          <CssBaseline />
          <CustomLayout>{children}</CustomLayout>
        </RecoilRoot>
      </body>
    </html>
  );
}
