export const componentList = [
  {
    label: "UI Elements",
    summary: "기본 UI 요소로 화면 구성에 필요한 단위 컴포넌트.",
    lists: [
      {
        label: "CustomButton",
        isDone: true,
        type: "custombutton",
        summary: "사용자 동작을 유도하는 버튼.",
      },
      {
        label: "CustomIcon",
        isDone: false,
        type: "customicon",
        summary: "아이콘을 표시하기 위한 컴포넌트.",
      },
      {
        label: "CustomChip",
        isDone: true,
        type: "customchip",
        summary: "작은 태그 형태로 상태나 속성을 표시.",
      },
      {
        label: "CustomBadge",
        isDone: false,
        type: "custombadge",
        summary: "숫자나 알림 상태를 강조 표시.",
      },
      {
        label: "CustomAvatar",
        isDone: false,
        type: "customavatar",
        summary: "사용자 프로필 이미지를 표시.",
      },
      {
        label: "CustomToggleButton",
        isDone: true,
        type: "customtogglebutton",
        summary: "켜짐/꺼짐 상태를 전환하는 버튼.",
      },
      {
        label: "CustomButtonGroup",
        isDone: true,
        type: "custombuttongroup",
        summary: "",
      },
      {
        label: "CustomTooltip",
        isDone: false,
        type: "customtooltip",
        summary: "",
      },
    ],
  },
  {
    label: "Forms",
    summary: "사용자 입력을 처리하는 폼 관련 컴포넌트.",
    lists: [
      {
        label: "CustomInput",
        isDone: true,
        type: "custominput",
        summary: "텍스트 입력 필드.",
      },
      {
        label: "CustomRadio",
        isDone: true,
        type: "customradio",
        summary: "라디오 버튼 선택 필드.",
      },
      {
        label: "CustomCheckbox",
        isDone: true,
        type: "customcheckbox",
        summary: "체크박스를 이용한 선택 필드.",
      },
      {
        label: "CustomSelect",
        isDone: true,
        type: "customselect",
        summary: "드롭다운 형태의 선택 필드.",
      },
      {
        label: "CustomSwitch",
        isDone: true,
        type: "customswitch",
        summary: "켜짐/꺼짐 상태를 전환하는 스위치.",
      },
      {
        label: "CustomDatepicker",
        isDone: false,
        type: "customdatepicker",
        summary: "날짜를 선택할 수 있는 입력 필드.",
      },
      {
        label: "CustomTimepicker",
        isDone: false,
        type: "customtimepicker",
        summary: "시간을 선택할 수 있는 입력 필드.",
      },
      {
        label: "CustomSlider",
        isDone: true,
        type: "customslider",
        summary: "시간을 선택할 수 있는 입력 필드.",
      },
      {
        label: "CustomAutoComplete",
        isDone: false,
        type: "customautocomplete",
        summary: "",
      },
      {
        label: "CustomRating",
        isDone: false,
        type: "customrating",
        summary: "",
      },
      {
        label: "CustomTransfer",
        isDone: false,
        type: "customtransfer",
        summary: "",
      },
    ],
  },
  {
    label: "Data Display",
    summary: "데이터를 시각적으로 표현하는 컴포넌트.",
    lists: [
      {
        label: "CustomDatagrid",
        isDone: true,
        type: "customdatagrid",
        summary: "데이터를 표 형태로 표시.",
      },
      {
        label: "CustomTable",
        isDone: true,
        type: "customtable",
        summary: "테이블 형태로 데이터 표시.",
      },
      {
        label: "CustomAccordion",
        isDone: true,
        type: "customaccordion",
        summary: "접었다 펼 수 있는 콘텐츠 패널.",
      },
      {
        label: "CustomTab",
        isDone: true,
        type: "customtab",
        summary: "탭 형태로 콘텐츠를 분리 표시.",
      },
      {
        label: "CustomTreeView",
        isDone: false,
        type: "customtreeview",
        summary: "계층 구조 데이터를 트리 형태로 표시.",
      },
      {
        label: "CustomScheduler",
        isDone: true,
        type: "customscheduler",
        summary: "일정 관리 및 스케줄링 도구.",
      },
      {
        label: "CustomPdfViewer",
        isDone: false,
        type: "custompdfviewer",
        summary: "PDF 파일을 뷰어로 표시.",
      },
      {
        label: "CustomCarousel",
        isDone: true,
        type: "customcarousel",
        summary: "이미지나 콘텐츠를 회전하여 보여주는 Carousel.",
      },
      {
        label: "CustomAppbar",
        isDone: false,
        type: "customappbar",
        summary: "이미지나 콘텐츠를 회전하여 보여주는 Carousel.",
      },
    ],
  },
  {
    label: "Feedback",
    summary: "사용자와의 상호작용 결과를 표시하는 컴포넌트.",
    lists: [
      {
        label: "CustomModal",
        isDone: true,
        type: "custommodal",
        summary: "팝업 형태로 추가 정보를 표시.",
      },
      {
        label: "CustomAlert",
        isDone: false,
        type: "customalert",
        summary: "",
      },
      {
        label: "CustomProgress",
        isDone: false,
        type: "customprogress",
        summary: "",
      },
      {
        label: "CustomSkeleton",
        isDone: false,
        type: "customskeleton",
        summary: "",
      },
      {
        label: "CustonSnackbar",
        isDone: false,
        type: "custonsnackbar",
        summary: "",
      },
    ],
  },
  {
    label: "Navigation",
    summary: "화면 간 이동 및 구조 제공을 위한 컴포넌트.",
    lists: [
      {
        label: "CustomMenu",
        isDone: false,
        type: "custommenu",
        summary: "메뉴 목록으로 화면 간 이동 제공.",
      },
      {
        label: "CustomBreadcrumbs",
        isDone: false,
        type: "custombreadcrumbs",
        summary: "",
      },
      {
        label: "CustomDrawer",
        isDone: false,
        type: "customdrawer",
        summary: "",
      },
      {
        label: "CustomPagination",
        isDone: false,
        type: "custompagination",
        summary: "",
      },
      {
        label: "CustomStepper",
        isDone: false,
        type: "customstepper",
        summary: "",
      },
    ],
  },
  {
    label: "Utility",
    summary: "특정 동작이나 상호작용을 지원하는 유틸리티 컴포넌트.",
    lists: [
      {
        label: "CustomSearch",
        isDone: true,
        type: "customsearch",
        summary: "검색 필드를 제공하여 데이터를 필터링.",
      },
    ],
  },
];
